# Generated by Django 4.1.5 on 2023-04-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_task_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
    ]
