# Generated by Django 4.1.5 on 2023-05-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_task_management', '0003_alter_task_assignee_alter_task_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
