# Generated by Django 4.1.5 on 2023-05-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_task_management', '0004_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
