# Generated by Django 4.1.5 on 2023-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_task_management', '0004_taskformember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskformember',
            options={},
        ),
        migrations.AddField(
            model_name='team',
            name='company_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
