# Generated by Django 4.1.5 on 2023-05-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_task_management', '0005_alter_taskformember_options_team_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskformember',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='taskformember',
            name='team_member',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskForMember',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
