# Generated by Django 4.1.5 on 2023-06-19 18:58

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingUserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=400)),
                ('org_name', models.CharField(max_length=400)),
                ('owner', models.CharField(max_length=400)),
                ('data_type', models.CharField(max_length=400)),
                ('profile_info', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=400)),
                ('data_type', models.CharField(max_length=100)),
                ('project_list', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskformember',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='taskformember',
            name='team_member',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskForMember',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
