# Generated by Django 4.1.5 on 2023-09-02 02:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_settinguserprofileinfo_userproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='settingUsersubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_project', models.CharField(max_length=100)),
                ('sub_project_list', jsonfield.fields.JSONField(default=dict)),
                ('company_id', models.CharField(max_length=400)),
                ('data_type', models.CharField(max_length=100)),
            ],
        ),
    ]
