# Generated by Django 4.1.5 on 2023-09-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_settingusersubproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='settingUsersubProject',
            new_name='UsersubProject',
        ),
    ]
