# Generated by Django 4.1.5 on 2023-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_settingusersubproject_usersubproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubproject',
            name='link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
