# Generated by Django 4.1.5 on 2023-09-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usersubproject_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubproject',
            name='link_id',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
