# Generated by Django 4.1.5 on 2023-09-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usersubproject_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubproject',
            name='link_id',
        ),
    ]
