# Generated by Django 4.1.5 on 2023-11-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_groupleadagenda_monthlytaskdata_personalinfo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupLeadAgenda',
        ),
    ]
