# Generated by Django 4.1.5 on 2023-11-16 01:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_groupleadagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinguserprofileinfo',
            name='profile_info',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project_list',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='usersubproject',
            name='sub_project_list',
            field=jsonfield.fields.JSONField(),
        ),
    ]
