# Generated by Django 4.1.5 on 2023-11-20 06:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_groupleadagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='inactive_project_list',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
