# Generated by Django 4.1.6 on 2023-03-30 11:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settinguserprofileinfo',
            name='project_list',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
