# Generated by Django 4.1.5 on 2023-02-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settinguserprofileinfo',
            old_name='new_version',
            new_name='data_type',
        ),
        migrations.RemoveField(
            model_name='settinguserprofileinfo',
            name='version',
        ),
    ]
