# Generated by Django 4.1.6 on 2023-03-30 11:35

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_settinguserprofileinfo_project_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=400)),
                ('data_type', models.CharField(max_length=100)),
                ('project_list', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
