# Generated by Django 4.1.6 on 2023-03-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_userproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settinguserprofileinfo',
            name='project_list',
        ),
    ]
